### ISSUE TITLE
Parameter endpoint tidak jelas

### ISSUE THREAD

**Issue by ReinhartC** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-huda-findryan-fatimatus#1]
Pada endpoint `/apitambahjadwal`, ada beberapa parameter yang tidak jelas formatnya.
1. matkul: *id_matkul* atau *nama_matkul*
2. waktu_mulai dan waktu_selesai: format waktu yang diterima kurang jelas. Mohon berikan contoh.

**Comment by hudafauzanm** [comment]
Sebelum terima kasih infonya,nanti akan diberitahukan lagi untuk input parameternya
