### ISSUE TITLE
Endpoint tidak ada

### ISSUE THREAD

**Issue by rogojagad** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-huda-findryan-fatimatus#2]
Endpoint `/apitambahjadwal` tidak ditemukan (not found), tetapi di dokumentasi sudah ada. Mohon dicek lagi.

**Comment by hudafauzanm** [comment]
baik terima kasih untuk infonya,akan segera di tindak lanjuti

**Comment by findryankp** [comment]
maaf ternyata salah merge dan hilang codenya

**Comment by rogojagad** [comment]
sip mantap
suwun, nanti kita cek lagi
